name: CI

on:
  pull_request:
    branches:
      - master
      - development

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_REGISTRY: https://registry.npmjs.org

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
          cache: 'npm'

      - run: npm ci

      - run: npm run ci
